#' SIMULATION STUDY CODE FOR: 
#' Rank-based estimators of global treatment effects for 
#' cluster randomized trials with multiple endpoints of different types
#' 
#' Author: Emma Davies Smith, esmith at hsph.harvard.edu
#' Date: 23 OCT 2024

# Load required libraries and source scripts
source('dependencies.R')

# Import simulation scenarios (generated by scenarios.R)
scenarios <- read.csv('./out/scenarios.csv')

# Simulate scenarios and store results 
results   <- simScenarios(scenarios, out='simResults.csv', seed=12345)

